name: "Hola mundooo"

on:
  push:
    branches: ["main"]

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
  otro-job:
    needs: deploy-cf
    runs-on: ubuntu-latest
    steps:
      - run: echo "ola"
      - run: echo "Este es un secreto: + ${{ secrets.TOKEN_SECRET }}"