name: "Hola mundooo"

on:
  push:
    branches: ["main"]

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      - run: echo "Hacemos pull del codigo"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar version"
  otro-job:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkeout@v4
      - run: echo "ola"